### ISSUE TITLE
我非常喜欢您的工作，但我想添加自己的设计的IOU_loss，请问需要修改哪些文件呢？

### ISSUE THREAD

**Issue by LuZeking** [DataXujing/DIoU_YOLO_V3#1]
我在parser.c中看到了IOU_loss声明，在box.c中找到了DIOU_loss算法的内容。
那么我想要添加自己的IOU_loss还需要修改哪些文件呢？

或是否可以像AlexeyAB增加giou那样，修改如下网页中的文件呢？
https://github.com/AlexeyAB/darknet/commit/6e13527f06480505556455dd9aad34d627a74501

期待您的回复

**Comment by DataXujing** [comment]
可以的，如果添加自己定义的loss可以在box.c中进行定义，然后在配置文件中修改就可以了，这个过程和`AlexeyAB/darknet`是完全一样的，现在`AlexeyAB/darknet`也支持D/CIoU loss和GIoU loss, 该项目同时也支持GIoU loss

**Comment by LuZeking** [comment]
好的，非常感谢您的解答



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "徐静"<notifications@github.com&gt;; 
发送时间: 2019年12月24日(星期二) 中午11:39
收件人: "DataXujing/DIoU_YOLO_V3"<DIoU_YOLO_V3@noreply.github.com&gt;; 
抄送: "陆泽金"<1206963586@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DataXujing/DIoU_YOLO_V3] 我非常喜欢您的工作，但我想添加自己的设计的IOU_loss，请问需要修改哪些文件呢？ (#1)




可以的，如果添加自己定义的loss可以在box.c中进行定义，然后在配置文件中修改就可以了，这个过程和AlexeyAB/darknet是完全一样的，现在AlexeyAB/darknet也支持D/CIoU loss和GIoU loss, 该项目同时也支持GIoU loss
